config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#landing'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true
  before_save(:titleize_name)

  scope :usa, -> { where(country_of_origin: "USA")}
  scope :three_most_recent, -> { order(created_at: :desc).limit(3) }
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}


  private
    def titleize_name
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates_length_of :content_body, in: 50..250
  validates :rating, presence: true
  validates_numericality_of :rating, greater_than: 0, less_than: 6
  before_save(:titleize_author)

  private
    def titleize_author
      self.author = self.author.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin?
  protect_from_forgery with: :exception
  before_action :authenticate_user! 

  before_action :configure_permitted_parameters, if: :devise_controller?

  def is_admin?
    current_user && current_user.admin
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password)}
    end 
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :only => [:new, :edit, :create, :update, :destroy] do
    flash[:alert] = "UNAUTHORIZED ACCESS: Please log-in with an admin account to access that resource." unless is_admin?
    redirect_to root_path unless is_admin?
  end

  def landing
    @products = Product.all
    @usa = Product.usa
    @threecent = Product.three_most_recent
    @popular = Product.most_reviews
    render :landing
  end

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:alert] = "Errors detected! Please resolve the issues and try again."
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:alert] = "Errors detected! Please resolve the issues and try again."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product removed successfully!"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :only => [:edit, :update, :destroy] do
    flash[:alert] = "UNAUTHORIZED ACCESS: Please log-in with an admin account to access that resource." unless is_admin?
    redirect_to root_path unless is_admin?
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review created successfully!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "Errors detected! Please resolve the issues and try again."
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review updated successfully!"
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      flash[:alert] = "Errors detected! Please resolve the issues and try again."
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review removed successfully!"
    redirect_to product_path(@review.product)
  end

  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :class => 'form-control' %>
  <%= f.label :cost %>
  <%= f.number_field :cost, :class => 'form-control' %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin, :class => 'form-control' %>
  <hr>
  <%= f.submit 'Submit!', :class => "btn btn-success" %>
<% end %>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field(:author, :class => 'form-control') %>
  <%= f.label :content_body %>
  <%= f.text_area(:content_body, :class => 'form-control') %>
  <%= f.label :rating %>
  <%= f.number_field :rating, in: 1..5, :class => 'form-control' %>
  <hr>
  <%= f.submit 'Submit!', :class => "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super Mario's Super Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'mario.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <br>
    <div class="registration">
      <% if user_signed_in? %>
        <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-warning" %>
        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Sign-In/Sign-Up", new_user_session_path, class: "btn btn-info" %>
      <% end %>
      <% if current_user %>
        <strong><%= current_user.email %></strong>
        <% if is_admin? %>
          <em> Administrative access granted! </em>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="jumbotron">
      <h1><a href="/">Super Mario's Super Foods</a> <%= image_tag("chef.png") %></h1>
    </div>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<h3><%= @product.name %></h3>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<% if is_admin? %>
  <%= link_to "Add new product", new_product_path, :class => "btn btn-primary" %>
<% end %>
<h1>All Products</h1>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> - $<%= product.cost %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

app/views/products/landing.html.erb
<h4>Welcome to Super Mario's Super Website for his Super Foods! Here's a few noteworthy products we offer!</h4>

<%= link_to "View all products", products_path, :class => "btn btn-success" %>

<% if @popular.any? %>
<h2>Most Reviewed Product: <strong><em><%= link_to @popular.first.name, product_path(@popular.first) %></em></strong> with <%= @popular.first.reviews.length %> reviews!</h2>
<% end %>

<h3>Most Recent Products</h3>
<% if @threecent.any? %>
  <ul>
    <% @threecent.each do |product| %>
      <li><%= link_to product.name, product_path(product) %> - <em><%= product.created_at %></em></li>
    <% end %>
  </ul>
<% end %>

<h2>Local Products Made in the USA</h2>
<% if @usa.any? %>
  <ul>
    <% @usa.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% end %>
<hr>
<h4><em>Our glorious founder</em></h4>
<br>
<%= image_tag("mario.png") %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3>Country of Origin: <%= @product.country_of_origin %></h3>
<h2>$<%= @product.cost %></h2>

<% if @product.reviews.any? %>
  <h4>Here is what some people are saying about <%= @product.name %>:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>'s review - <%= review.rating %>/5 stars
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.
<% end %>
<hr>
<%= link_to "Add a review", new_product_review_path(@product), :class => "btn btn-success" %>
<% if is_admin? %>
  <%= link_to "Edit product", edit_product_path(@product), :class => "btn btn-warning" %>
  <%= link_to "Delete product", product_path(@product), :class => "btn btn-danger", 
                                                          :data => {:confirm => "Are you sure?",
                                                                    :method => "delete"} %>
<% end %>
<%= link_to "Return to all products", products_path, :class => "btn btn-info" %>

app/views/reviews/edit.html.erb
<h1>Edit <%= @review.author %>'s review for <%= @product.name %>:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new review for <%= @product.name %>:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1><%= @review.author %>'s review of <%= @product.name %>:</h1>
<h3>Rating: <%= @review.rating %> out of 5</h3>
<p><%= @review.content_body %></p>
<hr>
<% if is_admin? %>
  <%= link_to "Edit review", edit_product_review_path(@product, @review), :class => "btn btn-warning" %>
  <%= link_to "Delete this review", product_review_path(@product, @review), :class => "btn btn-danger", 
                                                                  :data => {:confirm => "Are you sure?",
                                                                            :method => "delete"} %>
<% end %>
<%= link_to "Return to the product", product_path(@product), :class => "btn btn-info" %>
<% if @review.author == "Rick Astley" %>
<%= link_to "You should know better...", "http://bitly.com/98K8eH", :class => "btn" %>
<% end %>